-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.combustivel
(
    id_combustivel serial NOT NULL,
    nome_combustivel character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT combustivel_pkey PRIMARY KEY (id_combustivel),
    CONSTRAINT combustivel_nome_combustivel_key UNIQUE (nome_combustivel)
);

CREATE TABLE IF NOT EXISTS public.endereco
(
    id_endereco serial NOT NULL,
    nome_bairro character varying(100) COLLATE pg_catalog."default",
    nome_rua character varying(100) COLLATE pg_catalog."default",
    numero character varying(5) COLLATE pg_catalog."default",
    CONSTRAINT endereco_pkey PRIMARY KEY (id_endereco)
);

CREATE TABLE IF NOT EXISTS public.pesquisa
(
    id_pesquisa serial NOT NULL,
    id_posto integer NOT NULL,
    data_pesquisa timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pesquisa_pkey PRIMARY KEY (id_pesquisa)
);

CREATE TABLE IF NOT EXISTS public.pesquisa_combustivel
(
    id_pesquisa integer NOT NULL,
    id_combustivel integer NOT NULL,
    valor numeric(10, 2) NOT NULL,
    CONSTRAINT pesquisa_combustivel_pkey PRIMARY KEY (id_pesquisa, id_combustivel)
);

CREATE TABLE IF NOT EXISTS public.posto
(
    id_posto serial NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_endereco integer NOT NULL,
    CONSTRAINT posto_pkey PRIMARY KEY (id_posto)
);

ALTER TABLE IF EXISTS public.pesquisa
    ADD CONSTRAINT pesquisa_id_posto_fkey FOREIGN KEY (id_posto)
    REFERENCES public.posto (id_posto) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pesquisa_combustivel
    ADD CONSTRAINT pesquisa_combustivel_id_combustivel_fkey FOREIGN KEY (id_combustivel)
    REFERENCES public.combustivel (id_combustivel) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pesquisa_combustivel
    ADD CONSTRAINT pesquisa_combustivel_id_pesquisa_fkey FOREIGN KEY (id_pesquisa)
    REFERENCES public.pesquisa (id_pesquisa) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.posto
    ADD CONSTRAINT fk_endereco FOREIGN KEY (id_endereco)
    REFERENCES public.endereco (id_endereco) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

END;